- hosts: localhost
  connection: local
  tasks:
    - name: create containers
      lxd_container:
        name: "{{ item }}"
        state: started
        source:
          type: image
          fingerprint: 8b51ee006f13446fbd0b753c88ec367b699183bbb357dbfee487aa39b6447042
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
      with_items:
        - salt-master01
        - salt-minion01
        - salt-minion02
        - salt-minion03
        - salt-minion04
