- hosts: salt-minions
  tasks:
    - name: add apt-keys
      apt_key: url=http://apt.tcpcloud.eu/public.gpg state=present

    - name: update apt's cache
      apt: update_cache=yes

    - name: add tcpcloud repos
      apt_repository: repo="deb [arch=amd64] http://apt.tcpcloud.eu/nightly/ trusty main security extra tcp tcp-salt" state=present

    - name: install salt-minion and reclass
      apt: name={{item}} state=installed
      with_items:
        - salt-common
        - salt-minion
        - reclass
        - reclass-doc
        - python-reclass

    - name: point minion to master
      copy: src=files/master.conf dest=/etc/salt/minion.d/master.conf owner=root group=root mode=644

    - name: restart salt-minion service
      service: name=salt-minion state=restarted