- hosts: localhost
  connection: local
  tasks:
    - name: Update APT
      apt: update_cache=yes

    - name: Install LXD
      apt: name={{item}} state=installed
      with_items:
        - lxd
        - lxd-tools